export const pageStyles = {
  page: {
    minHeight: '100vh',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
    color: 'white',
    fontFamily: 'sans-serif',
  },
  panel: {
    width: '100%',
    maxWidth: 520,
    background: 'rgba(0,0,0,0.45)',
    border: '1px solid rgba(255,255,255,0.2)',
    borderRadius: 12,
    padding: 24,
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },
  panelWide: {
    width: '100%',
    maxWidth: 860,
    background: 'rgba(0,0,0,0.45)',
    border: '1px solid rgba(255,255,255,0.2)',
    borderRadius: 12,
    padding: 24,
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },
  title: {
    fontSize: 30,
  },
  subtitle: {
    fontSize: 24,
  },
  lead: {
    lineHeight: 1.7,
    opacity: 0.9,
  },
  primaryLink: {
    display: 'inline-block',
    width: 'fit-content',
    textDecoration: 'none',
    color: '#111',
    background: '#7ee787',
    fontWeight: 700,
    borderRadius: 8,
    padding: '10px 18px',
  },
  backLink: {
    width: 'fit-content',
    color: 'white',
    textDecoration: 'underline',
  },
  cardGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(210px, 1fr))',
    gap: 12,
  },
  card: {
    border: '1px solid rgba(255,255,255,0.25)',
    borderRadius: 10,
    padding: 12,
    background: 'rgba(255,255,255,0.04)',
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  cardTitle: {
    fontSize: 17,
    minHeight: 48,
  },
  thumbnail: {
    height: 92,
    border: '1px dashed rgba(255,255,255,0.4)',
    borderRadius: 8,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'rgba(255,255,255,0.8)',
  },
  secondaryLink: {
    textDecoration: 'none',
    color: 'white',
    border: '1px solid rgba(255,255,255,0.5)',
    borderRadius: 8,
    padding: '8px 12px',
    textAlign: 'center',
  },
  tabRow: {
    display: 'flex',
    gap: 8,
  },
  tabButton: {
    border: '1px solid rgba(255,255,255,0.4)',
    background: 'transparent',
    color: 'white',
    borderRadius: 8,
    padding: '8px 12px',
    cursor: 'pointer',
  },
  tabButtonActive: {
    background: '#f0c040',
    color: '#222',
    borderColor: '#f0c040',
    fontWeight: 700,
  },
  infoBox: {
    background: 'rgba(255,255,255,0.04)',
    border: '1px solid rgba(255,255,255,0.15)',
    borderRadius: 10,
    padding: 16,
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    lineHeight: 1.7,
  },
  actionRow: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 12,
  },
  outlineButton: {
    border: '1px solid rgba(255,255,255,0.5)',
    background: 'transparent',
    color: 'white',
    borderRadius: 8,
    padding: '10px 16px',
    cursor: 'pointer',
  },
  primaryButton: {
    border: 'none',
    background: '#7ee787',
    color: '#111',
    borderRadius: 8,
    fontWeight: 700,
    padding: '10px 16px',
    cursor: 'pointer',
  },
}